algoritmo "semnome"
var
   D, C, S: Inteiro
inicio
Escreval("================")
Escreval("      MENU      ")
Escreval("================")
Escreval(" [1] De 1 a 10  ")
Escreval(" [2] De 10 a 1  ")
Escreval(" [3] Sair       ")
Escreval("================")
Leia(D)
C <- 1
Repita
      Escolha
      Caso 1
           Enquanto (C < 10) faca
           Escreval(C)
           C <- C + 1
           FimEnquanto (C = 10)
      FimEscolha
Ate
fimalgoritmo
